training:
    fp16: True
    random_seed: 123
    num_gpus_per_node: 1
    batch_size: 32
    gradient_accumulation_batches: 1
    resume:
        resume: False
    checkpointing:
        directory: "Checkpoints"
        steps_interval: -1
        seconds_interval: -1
        num_checkpoints_to_keep: 1000
        keep_checkpoint_every_num_seconds: 86400
    logging:
        level: "INFO"
        steps_interval: -1 # disabled when negative
        seconds_interval: 2 # disabled when `steps_interval` is set
    optimization:
        optimizer_name: AdamW
        learning_rate: 2e-5
        weight_decay: 0.01
        max_gradient_norm: -1
    scheduler:
        scheduler_name: WarmupLinear
        warmup_steps: 1000
    evaluation:
        batch_size: 32
        seconds_interval: -1
        steps_interval: -1 # -1 for after every epoch, but will be disabled if total_num.epochs = -1
        after_num_steps: 0
    total_num:
        epochs: 10
        update_steps: -1 # disabled when total_num_epochs > 0