text_ppo:
    batch_size: None # it should be set in the training batch size
    ppo_buffer_size: 128
    sample_batch_size: 32
    ppo_mini_batch_size: 8
    ppo_epoch: 1
    ppo_epsilon: 0.2
    mix_human_demo: 1
    mix_human_demo_init_ratio: 0.5
    mix_human_demo_ratio_decay: 1.0
    # whehter a human demostration's reward is determined by the reward function
    constant_human_demo_reward: False