subconfigs:
    - model: roberta-tokenized-gpt2
    - training: ${task.name}
    - task: ${task.name}
flyconfig:
    run:
        # Specify the working directory
        # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
        dir: ./outputs/${task.name}
task:
    name: WebQuestion

# tasks in ROCStories, CommonGEN