hydra:
    run: # specify the working directory
      dir: ./outputs/CommonGEN # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} #./outputs/exp1 # 
defaults:
    - hydra/job_logging: colorlog
    - hydra/hydra_logging: colorlog
    - training: CommonGEN
    - model: roberta-tokenized-gpt2
    - text_ppo: default
    - decode: default
task:
    name: CommonGEN
    data_dir: /home/wuqy1203/Desktop/Projects/TextGAIL/data/${task.name}

# DailyDialog, CommonGEN, SNLI
