defaults:
    - task: ${task.name}
    - training: ${task.name}  
    - model: roberta-tokenized-gpt2
    - decode: default
flyconfig:
    run:
        # Specify the working directory
        # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
        dir: ./outputs/${task.name}
task:
    name: COCO


# COCO, EMNLP_NEWS