hydra:
    run: # specify the working directory
      dir: ./outputs/CommonGEN # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} #./outputs/exp1 # 
defaults:
    - task: CommonGEN
    # - hydra/job_logging: colorlog
    # - hydra/hydra_logging: colorlog
    - training: CommonGEN
    - model: roberta-tokenized-gpt2
    - text_gail: CommonGEN
    - decode: default

# CommonGEN, ROCStories
